project:
  type: website
  output-dir: docs  # GitHub Pages用に出力先をdocsに設定

website:
  title: "Maximizing the Interpretation of Black-Box Models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/dataset.qmd
        text: Dataset
      - href: notebooks/demo_r.qmd
        text: R Demo
      - href: notebooks/demo_py.qmd
        text: Python Demo

format:
  html:
    theme: flatly
    code-fold: true
    toc: true
    toc-depth: 3
    number-sections: false

execute:
  freeze: auto
